// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyx2J-MFq5E9I0vaPASHixlYxoat6HGXk',
    appId: '1:891457659005:web:49c5c930f4171dd1f71114',
    messagingSenderId: '891457659005',
    projectId: 'budgetbuddy-31cae',
    authDomain: 'budgetbuddy-31cae.firebaseapp.com',
    storageBucket: 'budgetbuddy-31cae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2rR-qOKQeyGhP3KsOOzU4g0OtFLuA8dQ',
    appId: '1:891457659005:android:6a50e18da26f1114f71114',
    messagingSenderId: '891457659005',
    projectId: 'budgetbuddy-31cae',
    storageBucket: 'budgetbuddy-31cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvJ47FLYaIXrIGzaE_iHCdyFVZt4SpOJM',
    appId: '1:891457659005:ios:bee846b1038bd6bcf71114',
    messagingSenderId: '891457659005',
    projectId: 'budgetbuddy-31cae',
    storageBucket: 'budgetbuddy-31cae.appspot.com',
    iosBundleId: 'com.example.spendsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvJ47FLYaIXrIGzaE_iHCdyFVZt4SpOJM',
    appId: '1:891457659005:ios:00952e00ea6f345af71114',
    messagingSenderId: '891457659005',
    projectId: 'budgetbuddy-31cae',
    storageBucket: 'budgetbuddy-31cae.appspot.com',
    iosBundleId: 'com.example.spendsense.RunnerTests',
  );
}
